
@startuml

' skinparam linetype ortho

frame "byteProcess()" as pRcv {

  database "Main" as sMain

  database "Process Tree\nreceive" as sProc
  database "Command Response\nreceive" as sCmd
  database "Log Entry\nreceive" as sLog

  database "Save" as sLogSave
  database "Fragment\nsave" as sLogFrag

  database "Save" as sCmdSave
  database "Fragment\nsave" as sCmdFrag

  database "Save" as sProcSave
  database "Fragment\nsave" as sProcFrag
}

sMain -u-> sMain

sMain -u-> sProc : 11
sMain <-u- sProc

sMain -u-> sLog : 12
sMain <-u- sLog

sMain -d-> sCmd : 13
sMain <-d- sCmd

sProc -r-> sLogSave : 17
sProc -d-> sLogFrag : 0F

sCmd -l-> sCmdSave : 17
sCmd -r-> sCmdFrag : 0F

sLog -l-> sProcSave : 17
sLog -d-> sProcFrag : 0F

sLogSave -d-> sMain
sProcSave -d-> sMain

sLogFrag -r-> sMain
sProcFrag -l-> sMain

sMain <-d- sCmdSave
sMain <-d- sCmdFrag

footer **dataReceive()** - States\n(C) DSP-Crowd Electronics GmbH

@enduml

