
@startuml

' skinparam linetype ortho

database "Input Set R" as sIn
database "Positive" as sPos

frame "byteProcess()" as pRcv {

  database "Main" as sMain

  database "Data\nreceive" as sRcv
  database "Save" as sSave
  database "Fragment\nsave" as sFrag
}

sIn -> sMain

sMain --> sMain

sFrag --> sMain
sFrag <-- sRcv : 0F

sMain -> sRcv : "\t11, 12, 13"

sMain <-- sSave
sRcv --> sSave : 17
sRcv --> sRcv : D

sSave --> sPos

footer **dataReceive()** - States\n(C) DSP-Crowd Electronics GmbH

@enduml

