
@startuml

' skinparam linetype ortho
' scale 0.6

component PC as pPc {

	frame "Debugger" as pDbg
	frame "Application" as pApp

	pDbg <-[thickness=2]-> pApp
}

component "Microcontroller" {

	frame "<<Application>>" as pAppUc
}

pDbg <-> pAppUc : "COM1 or\n  /dev/ttyACM0"

footer **CodeOrb** - Motivation\n(C) DSP-Crowd Electronics GmbH

@enduml

