
@startuml

' skinparam linetype ortho

rectangle "Your Tools" as gTools {

	frame "Process Tree" as pTree
	frame "Log" as pLog
	frame "Command" as pCmd
}

frame "CodeOrb" as pGw {

	frame "<<SingleWireControlling()>>" as pSwc
	frame "<<TcpListening()>>" as pList
	frame "TcpTransfering()" as pTrans
	frame "RemoteCommanding()" as pCmdRemote
	frame "InfoGathering()" as pGather
}

component "Target" as pTarget {

	frame "<<SingleWireTransfering()>>" as pSwt
}

pTree <-[thickness=2]- pTrans
pLog <-[thickness=2]- pTrans
pCmd <-[thickness=2]-> pCmdRemote : "TCP/IP"

pList .l.> pTrans
pList .r.> pCmdRemote

pTrans <-[thickness=2]- pSwc
pCmdRemote <-[thickness=2]-> pSwc

pCmdRemote <-- pGather

pSwc <--> pSwt : "COM1 or\n/dev/ttyACM0"
pSwc <-> pGather

footer **Processing()** - Gateway overview\n(C) DSP-Crowd Electronics GmbH

@enduml

