
@startuml

' skinparam linetype ortho

component "Target" as pTarget

frame "SingleWireTransfering()\nGateway" as pGw {

  frame "<<SingleWireControlling()>>" as pSwt
  frame "<<TcpListening()>>" as pTcp
  frame "TcpTransfering()" as pTrans
  frame "RemoteCommanding()" as pCmdRemote {
    frame "<<TcpTransfering()>>" as pTrans2
  }
}

rectangle "Your Tools" as gTools {
  frame "Process Tree" as pTree
  frame "Log" as pLog
  frame "Command" as pCmd
}

pTarget <--> pSwt : "COM1 or\n/dev/ttyACM0"

pTcp ..> pTrans
pTcp ..> pCmdRemote

pSwt --> pTrans
pSwt <--> pTrans2

pTrans --> pTree
pTrans --> pLog
pTrans2 <--> pCmd : "TCP/IP"

footer **Processing()** - Gateway overview\n(C) DSP-Crowd Electronics GmbH

@enduml

