
@startuml

' skinparam linetype ortho

frame "SingleWireScheduling()" as pSched {

  frame "Client" as pClient

  frame "Send" as pSchedSend
  frame "Receive" as pSchedRcv

  pClient <-- pSchedRcv
  pClient --> pSchedSend

  pSchedRcv -r[hidden]- pSchedSend
}

frame "SingleWireTransfering()" as pTarget {

  frame "Application" as pApp

  frame "Send" as pTargetSend
  frame "Receive" as pTargetRcv

  database "Command\nInput Buffer" as sBufCmd

  pTargetSend <-- pApp
  pTargetRcv --> pApp

  pTargetRcv -> sBufCmd
}

pSchedSend --> pTargetRcv
pSchedRcv <-- pTargetSend

footer **CodeOrb** - Transfer Quad\n(C) DSP-Crowd Electronics GmbH

@enduml

