
@startuml

hide time-axis

concise "UART TX\nData from\nController (GW)" as ctrl
concise "UART RX\nData from\nTarget" as tar

@0
ctrl is {-}
tar is {-}

@+60
ctrl is {-}
tar is {-}

@+20
ctrl is "F1"

@+20
ctrl is "90"

@+20
ctrl is "Command"

@+80
ctrl is "17"

@+20
ctrl is {-}

@+40
ctrl is "F2"

@+20
ctrl is {-}
tar is "A3"

@+20
tar is "Command Response"

@+80
tar is "17"

@+20
tar is {-}

@+40
ctrl is "F2"

@+20
ctrl is {-}
tar is "A0"

@+20
tar is {-}

footer **SingleWireControling()** Controller to Target and back - Command and Response\n(C) DSP-Crowd Electronics GmbH

@enduml

