
name: ARM, RISC-V & MinGW

on:
  workflow_dispatch

jobs:

  linux-native-build-run:
    runs-on: ubuntu-latest
    steps:

# Toolchain + git

      - name: Update
        run: sudo apt update
      - name: Install build tools cross
        run: sudo apt install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf gcc-riscv64-linux-gnu g++-riscv64-linux-gnu mingw-w64
      - name: Setup mingw
        run: sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install build tools
        run: python -m pip install meson ninja

      - uses: actions/checkout@v4
      - name: Initialize git submodules
        run: git submodule update --init --recursive

# Cross

      - name: Setup build directory meson ARM
        run: meson setup --cross-file tools-dev/cross/meson-cross-arm.txt build-meson-arm
      - name: Build application meson ARM
        run: ninja -C build-meson-arm

      - name: Setup build directory meson RISC-V
        run: meson setup --cross-file tools-dev/cross/meson-cross-riscv.txt build-meson-riscv
      - name: Build application meson RISC-V
        run: ninja -C build-meson-riscv

      - name: Setup build directory meson MinGW
        run: meson setup --cross-file tools-dev/cross/meson-cross-mingw.txt build-meson-mingw
      - name: Build application meson MinGW
        run: ninja -C build-meson-mingw

