
name: Windows

on:
  workflow_dispatch

jobs:

  windows-native-build-run:
    runs-on: windows-latest
    steps:

# Toolchain + git

      - name: Set up Visual Studio Environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install build tools
        run: python -m pip install meson ninja

      - uses: actions/checkout@v4
      - name: Initialize git submodules
        run: git submodule update --init --recursive

# Native meson

      - name: Setup build directory meson
        run: meson setup build-meson-native
      - name: Build application meson
        run: ninja -C build-meson-native
      - name: Start application meson
        run: ./build-meson-native/codeorb --help

